### ISSUE TITLE
Deswizzling BC1/BC3 textures

### ISSUE THREAD

**Issue by Kriskras99** [ScanMountGoat/nutexb_swizzle#33]
Hi, great project!

I have some questions that I ran into when decoding BC1/BC3 textures.
1. Is my understanding of `BlockHeight` correct?: Block height is used for some GPU optimisation, where the height of the block is based on the pixel size of the textures. Thus for uncompressed textures it can be calculated using the height, and for block compressed textures it can be calculated using the height divided by the block size?
2. Is `bytes_per_pixel` a misnomer in case of block compressed textures? In the examples, BC7 uses the block size. Thus for BC1 that would be 8 bytes and for BC3 it would be 16 bytes. Should I read `bytes_per_pixel` as `bytes_per_smallest_unit` (or something similar).
3. Is there a way to make deswizzling deal with alignment? I have textures where the mipmaps are aligned on 512 bytes, so [`deswizzle_surface`](https://docs.rs/tegra_swizzle/latest/tegra_swizzle/surface/fn.deswizzle_surface.html#) to deswizzle the padding and miss the later mipmaps. Would a valid work around be to individually decode the mipmaps (i.e. always providing `mipmap_count == 1`)? Example where things go wrong at level 6:
```yaml
Level:         0        1        2        3        4        5        6        7        8        9
Offset:      0x0 0x4_0000 0x5_0000 0x5_4000 0x5_5000 0x5_5400 0x5_5600 0x5_5800 0x5_5a00 0x5_5c00
Size:   0x4_0000 0x1_0000   0x4000   0x1000    0x400    0x100     0x40     0x10     0x10     0x10
```
